/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/voitureCartoon/source/Unity2Skfb.gltf --transform 
Files: public/voitureCartoon/source/Unity2Skfb.gltf [47.54KB] > /home/oscar/Documents/ThreeJS_Projects/TempTest/Unity2Skfb-transformed.glb [620.18KB] (-1205%)
ExporterVersion: 2.2.1
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Unity2Skfb-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} >
      <group name="defaultScene">
        <mesh name="node_CARRERA_-1346" geometry={nodes['node_CARRERA_-1346'].geometry} scale={0.1} material={materials.CARRERA_4096} position={[0, -0.134, 0]}>
          <mesh name="node_left_door_gloss_-1370" geometry={nodes['node_left_door_gloss_-1370'].geometry} scale={1} material={materials.CARRERA_4096} position={[-0.937, 0.66, -0.737]}>
            <mesh name="node_left_door_-1420" geometry={nodes['node_left_door_-1420'].geometry} scale={0.1} material={materials.CARRERA_4096_MATTE}>
              <mesh name="node_left_door_glass_-1430" geometry={nodes['node_left_door_glass_-1430'].geometry} scale={0.1} material={materials.CARRERA_4096_GLASS} position={[0.283, 0, 0.685]} />
              <mesh name="node_left_mirror_-1432" geometry={nodes['node_left_mirror_-1432'].geometry} scale={0.1} material={materials.CARRERA_4096_MIRRORS} position={[-0.002, 0, 0.293]} />
            </mesh>
          </mesh>
          <mesh name="node_right_door_gloss_-1368" geometry={nodes['node_right_door_gloss_-1368'].geometry} scale={1} material={materials.CARRERA_4096} position={[0.938, 0.67, -0.737]}>
            <mesh name="node_right_door_-1412" geometry={nodes['node_right_door_-1412'].geometry} scale={0.1} material={materials.CARRERA_4096_MATTE}>
              <mesh name="node_right_door_glass_-1468" geometry={nodes['node_right_door_glass_-1468'].geometry} scale={0.1} material={materials.CARRERA_4096_GLASS} position={[-0.283, 0, 0.685]} />
              <mesh name="node_right_mirror_-1470" geometry={nodes['node_right_mirror_-1470'].geometry} scale={0.1} material={materials.CARRERA_4096_MIRRORS} position={[0.002, 0, 0.293]} />
            </mesh>
          </mesh>
          <mesh name="node_spoiler1_-1406" geometry={nodes['node_spoiler1_-1406'].geometry} scale={1} material={materials.CARRERA_4096}>
            <mesh name="node_spoiler2_-1422" geometry={nodes['node_spoiler2_-1422'].geometry} scale={0.1} material={materials.CARRERA_4096_MATTE} />
          </mesh>
        </mesh>
        <mesh name="node_tyre1_-1438" geometry={nodes['node_tyre1_-1438'].geometry}  material={materials.CARRERA_4096_MATTE} scale={0.1} position={[-0.084, -0.1, -0.12]}  />
        <mesh name="node_front_lamps_-1400" geometry={nodes['node_front_lamps_-1400'].geometry} scale={0.098} material={materials.CARRERA_4096_HEADLIGHTS} position={[-0, -0.131, -0.004]} />
        <mesh name="node_MIRRORS_-1424" geometry={nodes['node_MIRRORS_-1424'].geometry} scale={0.098} material={materials.CARRERA_4096_MIRRORS}  position={[-0, -0.131, -0.004]}/>
        <mesh name="node_rear_lamps_-1404" geometry={nodes['node_rear_lamps_-1404'].geometry} scale={0.098} material={materials.CARRERA_4096_lamps}  position={[-0, -0.131, -0.004]}/>
        <mesh name="node_windows_-1408" geometry={nodes['node_windows_-1408'].geometry} scale={0.1} material={materials.CARRERA_4096_GLASS}  />
      </group>
    </group>
  )
}

useGLTF.preload('/Unity2Skfb-transformed.glb')
